### ISSUE TITLE
`--syncopt` fails with `get_updates() takes exactly 4 arguments`

### ISSUE THREAD

**Issue by bzamecnik** [avolkov1/keras_experiments#12]
```
CUDA_VISIBLE_DEVICES=0,1 python cifar10_cnn_mgpu.py --mgpu --epochs=5 --syncopt
```

```
2017-09-29 18:19:10.220219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:05:00.0)
2017-09-29 18:19:10.220257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1070, pci bus id: 0000:06:00.0)
Not using data augmentation.
Traceback (most recent call last):
  File "cifar10_cnn_mgpu.py", line 351, in <module>
    main()
  File "cifar10_cnn_mgpu.py", line 308, in main
    callbacks=callbacks)
  File "/home/bzamecnik/miniconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1575, in fit
    self._make_train_function()
  File "/home/bzamecnik/miniconda2/lib/python2.7/site-packages/keras/engine/training.py", line 960, in _make_train_function
    loss=self.total_loss)
TypeError: get_updates() takes exactly 4 arguments (3 given)
```

- Keras 2.0.8

**Comment by avolkov1** [comment]
Thanks. I'll try to fix this.
